@apiUrl = http://127.0.0.1:8080/rooms

### Get all rooms
GET {{apiUrl}}

### Get one room
GET {{apiUrl}}/1

### Create new room
POST {{apiUrl}}
Content-Type: application/json

{
    "room_number": "103",
    "beds": 2,
    "price": 1500
}

### Update room
PATCH {{apiUrl}}/1
Content-Type: application/json

{
    "room_number": "101",
    "beds": 3,
    "price": 2000
}

### Delete room
DELETE {{apiUrl}}/2